# Generated by Django 4.1.7 on 2023-04-04 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorInfo',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='身份证号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('telephone', models.CharField(max_length=20, verbose_name='联系方式')),
                ('age', models.IntegerField(default=30, verbose_name='年龄')),
                ('sex', models.CharField(default='男', max_length=20, verbose_name='性别')),
            ],
        ),
        migrations.CreateModel(
            name='BookISBN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=50, verbose_name='图书ISBN')),
            ],
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='desc',
            field=models.TextField(default=' ', verbose_name='图书简介'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='image',
            field=models.ImageField(default='upload/default.png', upload_to='upload/%Y/%m', verbose_name='图书封面'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='ishot',
            field=models.BooleanField(default=False, verbose_name='是否畅销'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='moredesc',
            field=models.TextField(default=' ', verbose_name='更多介绍'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='autorinfo',
            field=models.ManyToManyField(to='book.autorinfo'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='bookisbn',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='book.bookisbn'),
            preserve_default=False,
        ),
    ]
